# Builds the macOS guest from scratch, unattended.
#
# Setup Assistant cannot be *skipped* without MDM, but it can be *driven*: the tart
# Packer plugin types into it, which is how the upstream cirruslabs images are made.
# This template is adapted from their vanilla-tahoe template, with three changes
# that matter here:
#
#   * the account password is a variable, so it can be a generated one rather than
#     the well-known "admin";
#   * the keyboard layout and time zone follow the host instead of US/UTC;
#   * Gatekeeper stays on. The upstream template disables it because it builds CI
#     images; this VM is for browsing, so weakening it would be backwards.
#
# The Apple Account sign-in is deliberately skipped here — it needs 2FA, so it stays
# an interactive step, done once in the finished VM.

packer {
  required_plugins {
    tart = {
      # Pinned, not ">= 1.16.0": packer resolves an open bound to whatever is newest
      # at build time, and there is no lock file here to record what that was.
      # renovate: datasource=github-releases depName=cirruslabs/packer-plugin-tart
      version = "1.21.0"
      source  = "github.com/cirruslabs/tart"
    }
  }
}

variable "vm_name" {
  type    = string
  default = "browser-vm"
}

variable "from_ipsw" {
  type        = string
  default     = "latest"
  description = "IPSW URL, or \"latest\". Must be macOS 15+ or the guest cannot use iCloud."
}

variable "username" {
  type    = string
  default = "admin"
}

variable "password" {
  type        = string
  sensitive   = true
  description = "Account password. Generated by bib; never type it by hand."
}

variable "cpu_count" {
  type    = number
  default = 4
}

variable "memory_gb" {
  type    = number
  default = 8
}

variable "disk_size_gb" {
  type    = number
  default = 100
}

variable "keyboard_layout_id" {
  type        = number
  default     = 19
  description = "HIToolbox KeyboardLayout ID. 19 is Swiss German, 0 is U.S. bib always passes the host's."
}

variable "keyboard_layout_name" {
  type        = string
  default     = "Swiss German"
  description = "HIToolbox KeyboardLayout Name — the display name, with the space."
}

variable "timezone" {
  type    = string
  default = "Europe/Zurich"
}

variable "authorized_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "The public key bib logs in with. Passed as PKR_VAR_authorized_key."
}

variable "host_private_key" {
  type        = string
  default     = ""
  sensitive   = true
  description = "The guest's host key, generated on the host so the first connection can be verified."
}

variable "host_public_key" {
  type      = string
  default   = ""
  sensitive = true
}

variable "timezone_city" {
  type        = string
  default     = "Zurich"
  description = "Setup Assistant's time-zone field searches for a city, not an Olson id."
}

source "tart-cli" "browser-vm" {
  from_ipsw    = var.from_ipsw
  vm_name      = var.vm_name
  cpu_count    = var.cpu_count
  memory_gb    = var.memory_gb
  disk_size_gb = var.disk_size_gb
  ssh_username = var.username
  ssh_password = var.password
  ssh_timeout  = "300s"

  # Virtualization.framework's install sometimes reports done a moment early.
  create_grace_time = "30s"
  # Keeping recovery leaves "softwareupdate" usable in the guest.
  recovery_partition = "keep"

  boot_command = [
    # hello, hola, bonjour, …
    "<wait60s><spacebar>",
    # Language. Typing "english" straight away lands on "English (UK)", because the
    # list already sits on "English"; stepping via another language avoids that.
    "<wait30s>italiano<esc>english<enter>",
    # Select Your Country or Region
    "<wait60s><click 'Select Your Country or Region'><wait5s>united states<leftShiftOn><tab><leftShiftOff><spacebar>",
    # Transfer Your Data to This Mac -> set up as new
    "<wait10s><tab><tab><tab><spacebar><tab><tab><spacebar>",
    # Written and Spoken Languages
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Accessibility
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Data & Privacy
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Create a Mac Account
    "<wait10s><tab><tab><tab><tab><tab><tab>browser-in-a-box<tab>${var.username}<tab>${var.password}<tab>${var.password}<tab><tab><spacebar><tab><tab><spacebar>",
    # VoiceOver on: the remaining panes are navigated by keyboard, and VoiceOver
    # makes the focus deterministic.
    "<wait120s><leftAltOn><f5><leftAltOff>",
    # Sign In with Your Apple ID -> skip; 2FA cannot be automated, so it is done
    # interactively later in the finished VM.
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar><up><spacebar>",
    # Are you sure you want to skip signing in with an Apple ID?
    "<wait10s><tab><spacebar>",
    # Terms and Conditions
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # I have read and agree …
    "<wait10s><tab><spacebar>",
    # Age Range -> Adult
    "<wait10s><tab><tab><tab><spacebar>",
    # Enable Location Services -> no
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    "<wait10s><tab><spacebar>",
    # Select Your Time Zone. This field wants a city, not an Olson id; the id is
    # applied properly by a provisioner below.
    "<wait10s><tab><tab><tab>${var.timezone_city}<enter><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Analytics -> no
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Screen Time -> later
    "<wait10s><tab><tab><spacebar>",
    # Siri -> no
    "<wait10s><tab><spacebar><leftShiftOn><tab><leftShiftOff><spacebar>",
    # FileVault -> off (the disk already lives inside the host's encrypted volume)
    "<wait10s><leftShiftOn><tab><tab><leftShiftOff><spacebar>",
    "<wait10s><tab><spacebar>",
    # Choose Your Look
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Update Mac Automatically
    "<wait10s><tab><tab><spacebar>",
    # Welcome to Mac
    "<wait30s><spacebar>",
    # VoiceOver off
    "<wait10s><leftAltOn><f5><leftAltOff>",
    # Full keyboard navigation, so System Settings can be driven below.
    "<wait10s><leftAltOn><spacebar><leftAltOff>Terminal<wait10s><enter>",
    "<wait10s><wait10s>defaults write NSGlobalDomain AppleKeyboardUIMode -int 3<enter>",
    # Turn on Remote Login, which is what lets bib take the guest over afterwards.
    "<wait10s>open '/System/Applications/System Settings.app'<enter>",
    "<wait120s>",
    "<wait10s><leftCtrlOn><f2><leftCtrlOff><right><right><right><down>Sharing<enter>",
    # Screen Sharing first, exactly as upstream does it: the Remote Login step below
    # counts tabs from the focus this leaves behind.
    "<wait10s><tab><tab><tab><tab><tab><spacebar>",
    "<wait10s>${var.password}<enter>",
    # Remote Login, which is what lets bib take the guest over afterwards.
    "<wait10s><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><spacebar>",
    "<wait10s><leftAltOn>q<leftAltOff>",
  ]
}

build {
  sources = ["source.tart-cli.browser-vm"]

  provisioner "shell" {
    inline = [
      # Keyboard layout. `defaults write` stores "KeyboardLayout ID" as a string in an
      # old-style plist and HIToolbox then ignores the entry, so PlistBuddy is used to
      # keep it an integer. Both the enabled and the selected list have to be written;
      # only writing the enabled one leaves the layout inactive.
      "PLIST=$HOME/Library/Preferences/com.apple.HIToolbox.plist",
      "for KEY in AppleEnabledInputSources AppleSelectedInputSources; do /usr/libexec/PlistBuddy -c \"Delete :$KEY\" \"$PLIST\" 2>/dev/null || true; /usr/libexec/PlistBuddy -c \"Add :$KEY array\" -c \"Add :$KEY:0 dict\" -c \"Add :$KEY:0:InputSourceKind string 'Keyboard Layout'\" -c \"Add :$KEY:0:'KeyboardLayout ID' integer ${var.keyboard_layout_id}\" -c \"Add :$KEY:0:'KeyboardLayout Name' string '${var.keyboard_layout_name}'\" \"$PLIST\"; done",
      "killall cfprefsd 2>/dev/null || true",
      # sudo has no tty under a provisioner, so the password goes in on stdin.
      "echo '${var.password}' | sudo -S systemsetup -settimezone ${var.timezone}",
      # Do not let the guest fall asleep mid-download.
      "echo '${var.password}' | sudo -S systemsetup -setsleep Off",
    ]
  }

  # bib reaches the guest by key, and checks the guest's host key against one it
  # generated itself — so both are installed here, exactly as the offline path
  # installs them. Without this, the `bib vm setup` this build tells you to run next
  # can never connect.
  #
  # 0700 before anything lands in it. The private key goes through this directory
  # rather than /tmp, so there is no moment when another local user could read it —
  # an upload cannot be given a mode, but it can be put somewhere unreadable.
  provisioner "shell" {
    inline = ["install -d -m 0700 ~/.ssh"]
  }

  # Uploaded, not interpolated. A key whose comment holds a single quote would end
  # the quoting of an inline command and the rest of it would run as shell — and the
  # one thing this file must never do is take key material for instructions. The
  # file provisioner never goes near a shell. `~` is not expanded by the upload, so
  # the path is written out.
  provisioner "file" {
    content     = "${var.authorized_key}\n"
    destination = "/Users/${var.username}/.ssh/authorized_keys"
  }

  provisioner "file" {
    content     = var.host_private_key
    destination = "/Users/${var.username}/.ssh/host_key"
  }

  provisioner "file" {
    content     = "${var.host_public_key}\n"
    destination = "/Users/${var.username}/.ssh/host_key.pub"
  }

  provisioner "shell" {
    inline = [
      "chmod 600 ~/.ssh/authorized_keys",
      # Content, not size: an empty key still leaves the newline above, so the file
      # is not empty and `test -s` called it installed. A build that got no key
      # finished and handed over a guest nothing can log into.
      "grep -q '[^[:space:]]' ~/.ssh/authorized_keys || { echo 'no authorized_key was passed; bib could never log in to this guest'; exit 1; }",
      # No newline is added to this one, so an empty value really is an empty file.
      "test -s ~/.ssh/host_key || { echo 'no host_private_key was passed; bib could not verify this guest'; exit 1; }",
      "echo '${var.password}' | sudo -S install -m 0600 -o root -g wheel ~/.ssh/host_key /etc/ssh/ssh_host_ed25519_key",
      "echo '${var.password}' | sudo -S install -m 0644 -o root -g wheel ~/.ssh/host_key.pub /etc/ssh/ssh_host_ed25519_key.pub",
      "rm -f ~/.ssh/host_key ~/.ssh/host_key.pub",
    ]
  }

  provisioner "shell" {
    inline = [
      # Prove the two things the guest is built for.
      "spctl --status | grep -q 'assessments enabled' || { echo 'Gatekeeper is off, it should not be'; exit 1; }",
      # Chrome and the clipboard agent are installed by 'bib vm setup', the same
      # way the offline path installs them — there is no second copy here to
      # drift out of step.
      # The same check as the guard above, at the end rather than at the cause: a
      # whole install ran in between, and this is the file the guest is reachable by.
      "grep -q '[^[:space:]]' ~/.ssh/authorized_keys || { echo 'authorized_keys holds no key'; exit 1; }",
      # Not `sudo -n true || ...`: whenever sudo happened not to need a password
      # the first half succeeded and the check itself was never run, so a host key
      # that failed to install still reported a successful build.
      "echo '${var.password}' | sudo -S test -s /etc/ssh/ssh_host_ed25519_key",
    ]
  }
}
