# Builds the macOS guest from scratch, unattended.
#
# Setup Assistant cannot be *skipped* without MDM, but it can be *driven*: the tart
# Packer plugin types into it, which is how the upstream cirruslabs images are made.
# This template is adapted from their vanilla-tahoe template, with three changes
# that matter here:
#
#   * the account password is a variable, so it can be a generated one rather than
#     the well-known "admin";
#   * the keyboard layout and time zone follow the host instead of US/UTC;
#   * Gatekeeper stays on. The upstream template disables it because it builds CI
#     images; this VM is for browsing, so weakening it would be backwards.
#
# The Apple Account sign-in is deliberately skipped here — it needs 2FA, so it stays
# an interactive step, done once in the finished VM.

packer {
  required_plugins {
    tart = {
      version = ">= 1.16.0"
      source  = "github.com/cirruslabs/tart"
    }
  }
}

variable "vm_name" {
  type    = string
  default = "chrome-vm"
}

variable "from_ipsw" {
  type        = string
  default     = "latest"
  description = "IPSW URL, or \"latest\". Must be macOS 15+ or the guest cannot use iCloud."
}

variable "username" {
  type    = string
  default = "admin"
}

variable "password" {
  type        = string
  sensitive   = true
  description = "Account password. Generated by cib; never type it by hand."
}

variable "cpu_count" {
  type    = number
  default = 4
}

variable "memory_gb" {
  type    = number
  default = 8
}

variable "disk_size_gb" {
  type    = number
  default = 100
}

variable "keyboard_layout" {
  type        = string
  default     = "com.apple.keylayout.SwissGerman"
  description = "Input source id, e.g. com.apple.keylayout.SwissGerman or .US"
}

variable "timezone" {
  type    = string
  default = "Europe/Zurich"
}

source "tart-cli" "chrome-vm" {
  from_ipsw    = var.from_ipsw
  vm_name      = var.vm_name
  cpu_count    = var.cpu_count
  memory_gb    = var.memory_gb
  disk_size_gb = var.disk_size_gb
  ssh_username = var.username
  ssh_password = var.password
  ssh_timeout  = "300s"

  # Virtualization.framework's install sometimes reports done a moment early.
  create_grace_time = "30s"
  # Keeping recovery leaves "softwareupdate" usable in the guest.
  recovery_partition = "keep"

  boot_command = [
    # hello, hola, bonjour, …
    "<wait60s><spacebar>",
    # Language. Typing "english" straight away lands on "English (UK)", because the
    # list already sits on "English"; stepping via another language avoids that.
    "<wait30s>italiano<esc>english<enter>",
    # Select Your Country or Region
    "<wait60s><click 'Select Your Country or Region'><wait5s>switzerland<leftShiftOn><tab><leftShiftOff><spacebar>",
    # Transfer Your Data to This Mac -> set up as new
    "<wait10s><tab><tab><tab><spacebar><tab><tab><spacebar>",
    # Written and Spoken Languages
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Accessibility
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Data & Privacy
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Create a Mac Account
    "<wait10s><tab><tab><tab><tab><tab><tab>chrome-in-a-box<tab>${var.username}<tab>${var.password}<tab>${var.password}<tab><tab><spacebar><tab><tab><spacebar>",
    # VoiceOver on: the remaining panes are navigated by keyboard, and VoiceOver
    # makes the focus deterministic.
    "<wait120s><leftAltOn><f5><leftAltOff>",
    # Sign In with Your Apple ID -> skip; 2FA cannot be automated, so it is done
    # interactively later in the finished VM.
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar><up><spacebar>",
    # Are you sure you want to skip signing in with an Apple ID?
    "<wait10s><tab><spacebar>",
    # Terms and Conditions
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # I have read and agree …
    "<wait10s><tab><spacebar>",
    # Age Range -> Adult
    "<wait10s><tab><tab><tab><spacebar>",
    # Enable Location Services -> no
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    "<wait10s><tab><spacebar>",
    # Select Your Time Zone
    "<wait10s><tab><tab><tab>${var.timezone}<enter><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Analytics -> no
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Screen Time -> later
    "<wait10s><tab><tab><spacebar>",
    # Siri -> no
    "<wait10s><tab><spacebar><leftShiftOn><tab><leftShiftOff><spacebar>",
    # FileVault -> off (the disk already lives inside the host's encrypted volume)
    "<wait10s><leftShiftOn><tab><tab><leftShiftOff><spacebar>",
    "<wait10s><tab><spacebar>",
    # Choose Your Look
    "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
    # Update Mac Automatically
    "<wait10s><tab><tab><spacebar>",
    # Welcome to Mac
    "<wait30s><spacebar>",
    # VoiceOver off
    "<wait10s><leftAltOn><f5><leftAltOff>",
    # Full keyboard navigation, so System Settings can be driven below.
    "<wait10s><leftAltOn><spacebar><leftAltOff>Terminal<wait10s><enter>",
    "<wait10s><wait10s>defaults write NSGlobalDomain AppleKeyboardUIMode -int 3<enter>",
    # Turn on Remote Login, which is what lets cib take the guest over afterwards.
    "<wait10s>open '/System/Applications/System Settings.app'<enter>",
    "<wait120s>",
    "<wait10s><leftCtrlOn><f2><leftCtrlOff><right><right><right><down>Sharing<enter>",
    "<wait10s><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><spacebar>",
    "<wait10s>${var.password}<enter>",
    "<wait10s><leftAltOn>q<leftAltOff>",
  ]
}

build {
  sources = ["source.tart-cli.chrome-vm"]

  provisioner "shell" {
    inline = [
      # Keyboard layout, so typing in the guest matches the host.
      "defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '{\"InputSourceKind\"=\"Keyboard Layout\"; \"KeyboardLayout ID\"=19; \"KeyboardLayout Name\"=\"SwissGerman\";}' || true",
      "defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string '${var.keyboard_layout}' || true",
      "sudo systemsetup -settimezone ${var.timezone} 2>/dev/null || true",
      # Do not let the guest fall asleep mid-download.
      "sudo systemsetup -setsleep Off 2>/dev/null || true",
    ]
  }

  provisioner "shell" {
    inline = [
      # Chrome, which is the entire point of the VM.
      "curl -fsSL -o /tmp/chrome.dmg 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg'",
      "hdiutil attach -nobrowse -quiet /tmp/chrome.dmg -mountpoint /tmp/chrome-mount",
      "cp -R '/tmp/chrome-mount/Google Chrome.app' /Applications/",
      "hdiutil detach -quiet /tmp/chrome-mount",
      "rm -f /tmp/chrome.dmg",
      "'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --version",
    ]
  }

  provisioner "shell" {
    inline = [
      # Prove the two things the guest is built for.
      "spctl --status | grep -q 'assessments enabled' || { echo 'Gatekeeper is off, it should not be'; exit 1; }",
      "test -d '/Applications/Google Chrome.app'",
    ]
  }
}
