# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `bib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Bib < Formula
  desc "A real, unmanaged browser in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/browser-in-a-box"
  version "3.0.1"
  license "MIT"

  on_macos do
    on_intel do
      # Only the container variant would work here anyway, and no Intel Mac binary
      # is published; say so instead of failing with a missing url.
      odie "bib ships macOS binaries for Apple silicon only; run ./bib.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.0.1/bib-macos-arm64.tar.gz"
      sha256 "ee84916b6880800ef1ccaabb8ffe97258f1c9a8aafe0c6e80daf8f5890bfef25"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.0.1/bib-linux-arm64.tar.gz"
      sha256 "0bace941fe23a618125eff5f1a83e0fd5ebd7298d09bf84975a4c873f6202044"
    end
    on_intel do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.0.1/bib-linux-x86_64.tar.gz"
      sha256 "3b3c03030e59dac40c5079f0e7361020bffba28a6a5de487bb1f90331071e07c"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bib"
  end

  test do
    assert_match "bib #{version}", shell_output("#{bin}/bib --version")
  end
end
