# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `bib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Bib < Formula
  desc "A real, unmanaged browser in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/browser-in-a-box"
  version "3.2.0"
  license "MIT"

  on_macos do
    on_intel do
      # Only the container variant would work here anyway, and no Intel Mac binary
      # is published; say so instead of failing with a missing url.
      odie "bib ships macOS binaries for Apple silicon only; run ./bib.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.0/bib-macos-arm64.tar.gz"
      sha256 "f874f7bfc36ebdab4c04c1ad51c4ed40c5f17d7c49ec11a0a7d77da04fce016d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.0/bib-linux-arm64.tar.gz"
      sha256 "02760d4df499080961dbee024bb323cd540a41ca156ae3a980db4b152614ccaa"
    end
    on_intel do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.0/bib-linux-x86_64.tar.gz"
      sha256 "650a77dc875062d61e25abe51e41d0593aac49bbc2bed51291345af7b1d51aab"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bib"
  end

  test do
    assert_match "bib #{version}", shell_output("#{bin}/bib --version")
  end
end
