# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `bib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Bib < Formula
  desc "A real, unmanaged browser in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/browser-in-a-box"
  version "3.2.1"
  license "MIT"

  on_macos do
    on_intel do
      # Only the container variant would work here anyway, and no Intel Mac binary
      # is published; say so instead of failing with a missing url.
      odie "bib ships macOS binaries for Apple silicon only; run ./bib.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.1/bib-macos-arm64.tar.gz"
      sha256 "b837d12f3a7916047d15b48dde83d98974589dfc17f32ec5093069244ac25be2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.1/bib-linux-arm64.tar.gz"
      sha256 "6db8ed61918b9c4d3c2dcbae610b5f286aa3eb26d5c0d379c369bfe7186c7c86"
    end
    on_intel do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.2.1/bib-linux-x86_64.tar.gz"
      sha256 "81bace3c06c85fa716a5af07cdd552344ec65ea80a326cf4beaf6a90e6fd64a9"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bib"
  end

  test do
    assert_match "bib #{version}", shell_output("#{bin}/bib --version")
  end
end
