# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `cib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Cib < Formula
  desc "Real Google Chrome in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/chrome-in-a-box"
  version "1.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.3.0/cib-macos-arm64.tar.gz"
      sha256 "be4de68af2de47ce22afd75fc93fcd3683e1b4b102b50d2133411a8b2ed713c9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.3.0/cib-linux-arm64.tar.gz"
      sha256 "6178aacbb0fb58a85c2961b04b09f1b01de48c44e91f83e121885c91730eebbd"
    end
    on_intel do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.3.0/cib-linux-x86_64.tar.gz"
      sha256 "75e1d32064af98050d37b36b09fbaa28711bf37b2a88a98c75c8bf10f8df7a93"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"cib"
  end

  test do
    assert_match "cib #{version}", shell_output("#{bin}/cib --version")
  end
end
