# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
class Cib < Formula
  desc "Real Google Chrome in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/chrome-in-a-box"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v0.0.0/cib-macos-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v0.0.0/cib-linux-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v0.0.0/cib-linux-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "cib"
  end

  test do
    assert_match "cib #{version}", shell_output("#{bin}/cib --version")
  end
end
